/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminMaintenanceRouteImport } from './routes/_admin/maintenance'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminAccountRouteImport } from './routes/_admin/account'
import { Route as AdminEventsModerationRouteImport } from './routes/_admin/events/moderation'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsModerationRoute = AdminEventsModerationRouteImport.update({
  id: '/events/moderation',
  path: '/events/moderation',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AdminAccountRoute
  '/dashboard': typeof AdminDashboardRoute
  '/maintenance': typeof AdminMaintenanceRoute
  '/users': typeof AdminUsersRoute
  '/events/moderation': typeof AdminEventsModerationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AdminAccountRoute
  '/dashboard': typeof AdminDashboardRoute
  '/maintenance': typeof AdminMaintenanceRoute
  '/users': typeof AdminUsersRoute
  '/events/moderation': typeof AdminEventsModerationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/account': typeof AdminAccountRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/maintenance': typeof AdminMaintenanceRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/events/moderation': typeof AdminEventsModerationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/dashboard'
    | '/maintenance'
    | '/users'
    | '/events/moderation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/dashboard'
    | '/maintenance'
    | '/users'
    | '/events/moderation'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/account'
    | '/_admin/dashboard'
    | '/_admin/maintenance'
    | '/_admin/users'
    | '/_admin/events/moderation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/maintenance': {
      id: '/_admin/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/account': {
      id: '/_admin/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/events/moderation': {
      id: '/_admin/events/moderation'
      path: '/events/moderation'
      fullPath: '/events/moderation'
      preLoaderRoute: typeof AdminEventsModerationRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminEventsModerationRoute: typeof AdminEventsModerationRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminEventsModerationRoute: AdminEventsModerationRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
