import { useMutation } from '@tanstack/react-query';
import { Redirect, Stack } from 'expo-router';
import { useEffect, useRef } from 'react';

import { UserRole } from '@CeolX/shared/enums';

import { appToast } from '@/components/AppToast';
import { useAuth } from '@/contexts/auth-context';
import { LocationOverrideProvider } from '@/contexts/location-override-context';
import { useFcmRegistration } from '@/hooks/use-fcm-registration';
import { useLocationSetupGate } from '@/hooks/use-location-setup-gate';
import { useMe } from '@/hooks/use-me';
import { trpc } from '@/utils/trpc';

export default function AppLayout() {
  const { user, isGuest, isLoading, isCompletingRegistration } = useAuth();

  // Register the device with FCM and wire foreground/background/cold-start
  // listeners (M7-T1). The hook is a no-op until the user is authenticated.
  useFcmRegistration();

  // Gates the standalone "Set your location" onboarding step (read once on mount).
  const locationGate = useLocationSetupGate();

  const {
    data: meData,
    isLoading: meLoading,
    isError: meError,
    refetch: meRefetch,
  } = useMe({ enabled: !!user && !isGuest });

  // Show toast + auto-retry when users.me fails — prevents onboarding guard bypass
  useEffect(() => {
    if (!meError) return;
    appToast.error('Something went wrong', 'Retrying your session…');
    void meRefetch();
  }, [meError, meRefetch]);

  // M11-T1 — fire the "deletion cancelled" toast once per login. The flag is
  // set by the BetterAuth session-create hook; we ack it on the server so it
  // doesn't re-fire on subsequent me refreshes within the same session.
  const acknowledgeNotice = useMutation(trpc.users.acknowledgeDeletionNotice.mutationOptions());
  const noticeShown = useRef(false);
  useEffect(() => {
    if (!meData?.deletionCancelledNotice || noticeShown.current) return;
    noticeShown.current = true;
    appToast.success('Welcome back', 'Your account deletion has been cancelled.');
    void acknowledgeNotice.mutateAsync().catch(() => {
      // Server ack failed — allow the toast to re-fire on next session.
      noticeShown.current = false;
    });
  }, [meData?.deletionCancelledNotice, acknowledgeNotice]);

  // Hold rendering while pendingRegistration is being consumed — otherwise the
  // spectator default flashes before completeRegistration patches the role.
  if (isLoading || isCompletingRegistration || (!!user && !isGuest && meLoading)) {
    return null;
  }

  if (!user && !isGuest) {
    return <Redirect href="/(auth)/sign-in" />;
  }

  if (user && !isGuest && meError) return null;

  // Redirect artist/venue users who haven't completed onboarding
  if (user && meData && !meData.onboardingComplete) {
    if (meData.currentRole === UserRole.ARTIST) {
      return <Redirect href="/(auth)/artist-onboarding" />;
    }
    if (meData.currentRole === UserRole.VENUE) {
      // Route type is generated by Expo Router — regenerates on next `expo start`
      return <Redirect href={'/(auth)/venue-onboarding'} />;
    }
  }

  // Location onboarding step — gated only AFTER profile onboarding so artist/venue
  // finish their profile first, then every persona (spectators have
  // onboardingComplete=true) lands on the standalone "Set your location" step
  // until they complete it.
  if (user && meData && meData.onboardingComplete) {
    if (locationGate === 'checking') return null;
    if (locationGate === 'needed') return <Redirect href={'/(auth)/set-location'} />;
  }

  return (
    <LocationOverrideProvider>
      <Stack screenOptions={{ headerShown: false }}>
        <Stack.Screen name="(tabs)" />
        <Stack.Screen name="add-location" options={{ presentation: 'modal' }} />
        <Stack.Screen name="events/create" />
        <Stack.Screen name="events/edit/[eventId]" />
        <Stack.Screen name="artist/[artistId]" />
        <Stack.Screen name="venue/[venueId]" />
        <Stack.Screen name="notifications" />
        <Stack.Screen name="change-password" />
      </Stack>
    </LocationOverrideProvider>
  );
}
