import { Redirect, Stack } from 'expo-router';
import { useEffect } from 'react';

import { UserRole } from '@CeolX/shared/enums';

import { appToast } from '@/components/AppToast';
import { useAuth } from '@/contexts/auth-context';
import { useMe } from '@/hooks/use-me';

export default function AppLayout() {
  const { user, isGuest, isLoading } = useAuth();

  const {
    data: meData,
    isLoading: meLoading,
    isError: meError,
    refetch: meRefetch,
  } = useMe({ enabled: !!user && !isGuest });

  // Show toast + auto-retry when users.me fails — prevents onboarding guard bypass
  useEffect(() => {
    if (!meError) return;
    appToast.error('Something went wrong', 'Retrying your session…');
    void meRefetch();
  }, [meError, meRefetch]);

  if (isLoading || (!!user && !isGuest && meLoading)) {
    return null;
  }

  if (!user && !isGuest) {
    return <Redirect href="/(auth)/sign-in" />;
  }

  if (user && !isGuest && meError) return null;

  // Redirect artist/venue users who haven't completed onboarding
  if (user && meData && !meData.onboardingComplete) {
    if (meData.currentRole === UserRole.ARTIST) {
      return <Redirect href="/(auth)/artist-onboarding" />;
    }
    if (meData.currentRole === UserRole.VENUE) {
      // Route type is generated by Expo Router — regenerates on next `expo start`
      return <Redirect href={'/(auth)/venue-onboarding'} />;
    }
  }

  return (
    <Stack screenOptions={{ headerShown: false }}>
      <Stack.Screen name="(tabs)" />
      <Stack.Screen name="events/create" />
      <Stack.Screen name="events/edit/[eventId]" />
      <Stack.Screen name="artist/[artistId]" />
      <Stack.Screen name="venue/[venueId]" />
      <Stack.Screen name="notifications" />
    </Stack>
  );
}
