name: Staging Android
on:
  push:
    branches: [development]
jobs:
  build:
    name: Build APK
    type: build
    params:
      platform: android
      profile: staging
  publish_update:
    name: Publish OTA
    type: update
    needs: [build]
    params:
      branch: staging
      message: ${{ github.event.head_commit.message }}
